PharmacyProject/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PharmacyProject.Data;
using PharmacyProject.Data.DataModels;
using PharmacyProject.Servises;
using PharmacyProject.Servises.Interfaces;
using PharmacyProject.VewModels;
using System;

namespace PharmacyProject.Controllers
{
    [Authorize]
    public class CartController : BaseController
    {
        private readonly ICartService _cartService;

        public CartController(ICartService cartService)
        {
            _cartService = cartService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var model = await _cartService.GetIndexAsync(GetUserId());

            if (model == null)
            {
                return View("CustomErrorView");
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(int id)
        {
            await _cartService.AddAsync(id, GetUserId());

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Remove(int medicineId)
        {
            await _cartService.RemoveAsync(medicineId, GetUserId());

            return RedirectToAction("Index");
        }

        
    }
}

PharmacyProject/Controllers/MedicineController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PharmacyProject.Data;
using PharmacyProject.Data.DataModels;
using PharmacyProject.Servises;
using PharmacyProject.Servises.Interfaces;
using PharmacyProject.VewModels;
using System;

namespace PharmacyProject.Controllers
{
    [Authorize]
    public class MedicineController : BaseController
    {
        private readonly IMedicineService _medicineService;

        public MedicineController(IMedicineService medicineService)
        {
            _medicineService = medicineService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var model = await _medicineService.GetIndex(GetUserId());

            if (model == null)
            {
                return View("CustomErrorView");
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var model = await _medicineService.GetAddModelAsynk();

            if (model == null)
            {
                return View("CustomErrorView");
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(MedicineViewModel viewModel)
        {
            if(ModelState.IsValid == false)
            {
                var model = await _medicineService.GetAddModelAsynk();
                return View(model);
            }

            await _medicineService.AddMedicineAsync(viewModel, GetUserId());

            return RedirectToAction("Index");
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var medicine = await _medicineService.GetDetails(id);

            if (medicine == null)
            {
                return View("CustomErrorView");
            }

            return View(medicine);
        }

        [HttpGet]
        public async Task<IActionResult> Assign(int medcineId)
        {
            var model = await _medicineService.GetAddMedcineToPharmacyViewModelAsync(medcineId, GetUserId());

            if (model == null)
            {
                return View("CustomErrorView");
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Assign(AddMedicineToPharmacyViewModel model)
        {
            if (ModelState.IsValid)
            {
                await _medicineService.AssignMedicineAsync(model);
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var model = await _medicineService.GetMedicineDeleteViewModel(id, GetUserId());

            if (model == null)
            {
                return View("CustomErrorView");
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(MedicineDeleteViewModel model)
        {
            await _medicineService.Delete(model.Id, model.PublisherId, GetUserId());

            return RedirectToAction("Index");
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Search()
        {
            var model = await _medicineService.GetSearchViewModel();

            if (model == null)
            {
                return View("CustomErrorView");
            }

            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> SearchResult(MedicineSearchViewModel model)
        {
            var result = await _medicineService.GetSearchResultAsync(model, GetUserId());

            if(result == null)
            {
                return View("CustomErrorView");
            }
            else if (result.Any() == false)
            {
                return View("CustomNotFoundView");
            }

            return View("Index", result);
        }


    }
}

PharmacyProject/Controllers/PharmacyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PharmacyProject.Data;
using PharmacyProject.Data.DataModels;
using PharmacyProject.Servises;
using PharmacyProject.Servises.Interfaces;
using PharmacyProject.VewModels;
using System;

namespace PharmacyProject.Controllers
{
    public class PharmacyController : BaseController
    {
        private readonly IPharmacyService _pharmacyService;

        public PharmacyController(IPharmacyService pharmacyService)
        {
            _pharmacyService = pharmacyService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var modelsCollection = await _pharmacyService.GetPharmaciesAsynk(GetUserId());

            if (modelsCollection == null)
            {
                return View("CustomErrorView");
            }

            return View(modelsCollection);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var model = _pharmacyService.GetPharmacyViewModel();

            if (model == null)
            {
                return View("CustomErrorView");
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(PharmacyViewModel model)
        {
            if(ModelState.IsValid == false)
            {
                return View(model);
            }

            await _pharmacyService.AddPharamcyToDatabaseAsync(model, GetUserId());

            return RedirectToAction("Index");
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var pharmacy = await _pharmacyService.GetDetailsAsync(id, GetUserId());

            if (pharmacy == null)
            {
                return View("CustomErrorView");
            }

            return View(pharmacy);
        }

        [HttpPost]
        public async Task<IActionResult> RemoveFromDetails(PharmacyMedicineViewModel model)
        {
            await _pharmacyService.RemoveFromDetailsAsync(model.Id, model.PharmacyId, GetUserId());

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var model = await _pharmacyService.GetPharmacyDeleteViewModel(id, GetUserId());

            if (model == null)
            {
                return View("CustomErrorView");
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(MedicineDeleteViewModel model)
        {
            await _pharmacyService.Delete(model.Id, GetUserId());

            return RedirectToAction("Index");
        }



    }
}

PharmacyProject/Views/Shared/CustomErrorView.cshtml
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title text-center">An Error Has occourred :-(</h3>
            </div>
            <div class="card-footer">
                <form asp-controller="Home" asp-action="Index" method="get" class="d-inline">
                    <button type="submit" class="btn btn-success w-100">Back to Home</button>
                </form>
            </div>
        </div>
    </div>
</div>

PharmacyProject/Views/Shared/CustomNotFoundView.cshtml
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title text-center">404 -> didn't find what you're looking for :-(</h3>
            </div>
            <div class="card-footer">
                <form asp-controller="Medicine" asp-action="Search" method="get" class="d-inline">
                    <button type="submit" class="btn btn-success w-100">Back to "Search" & try again</button>
                </form>
            </div>
        </div>
    </div>
</div>

PharmacyProject/Views/Shared/PageNotFoundView.cshtml
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title text-center">404 -> Page not found :-(</h3>
            </div>
            <div class="card-footer">
                <form asp-controller="Home" asp-action="Index" method="get" class="d-inline">
                    <button type="submit" class="btn btn-success w-100">Back to index page</button>
                </form>
            </div>
        </div>
    </div>
</div>

PharmacyProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PharmacyProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PharmacyProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PharmacyProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pharmacy" asp-action="Index">Pharmacies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Medicine" asp-action="Index">Medicines</a>
                        </li>
                        @if (User?.Identity?.IsAuthenticated ?? false)  // Only show if user is logged in
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Cart" asp-action="Index">Cart</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - PharmacyProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>